language: generic
sudo: false
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - evm list
  - evm use $EVM_EMACS
  - evm bin
  - which emacs
  - emacs --version
  - EMACS=`evm bin` cask
  - EMACS=`evm bin` cask install


env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-git-snapshot-travis


script:
  - emacs --version
  - EMACS=`evm bin` make test