language: generic
sudo: required
dist: trusty
group: deprecated-2017Q4

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - evm list
  - evm use $EVM_EMACS
  - evm bin
  - which emacs
  - emacs --version
  - EMACS=`evm bin` cask
  - EMACS=`evm bin` cask install


env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis
  - EVM_EMACS=emacs-git-snapshot-travis

matrix:
  allow_failures:
  - env: EVM_EMACS=emacs-26.1-travis
  - env: EVM_EMACS=emacs-git-snapshot-travis

script:
  - emacs --version
  - EMACS=`evm bin` make test
  - EMACS=`evm bin` make compile
